// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaginationApp.Data;

#nullable disable

namespace PaginationApp.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20230303185314_First")]
    partial class First
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PaginationApp.Data.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Several authors",
                            Genre = "Religious",
                            Title = "The Bible"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Mao Zedong",
                            Genre = "Political",
                            Title = "Quotations from Chairman Mao Tse-Tung"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Several authors",
                            Genre = "Religious",
                            Title = "The Quran"
                        },
                        new
                        {
                            Id = 4,
                            Author = "John Tolkien",
                            Genre = "Fantasy",
                            Title = "The Lord Of The Rings"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Antoine de Saint-Exupery",
                            Genre = "Children’s Novel",
                            Title = "The Little Prince"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Joanne Rowling",
                            Genre = "Fantasy",
                            Title = "Harry Potter and the Philosopher’s Stone"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Robert Baden-Powell",
                            Genre = "Manual / Instructional",
                            Title = "Scouting for Boys"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Agatha Christie",
                            Genre = "Mystery Crime",
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = 9,
                            Author = "John Tolkien",
                            Genre = "Fantasy",
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Cao Xueqin",
                            Genre = "Novel",
                            Title = "The Dream Of The Red Chamber"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
